print("TUPPLES")
print("Question1")
tup1=('python','geek',1,2,5,'riya')
print(tup1)
print("Length of tupple is",len(tup1))
print('*'*10)
print('\n')
print("Question2")
tup2=(66,12,8,56,23,100)
print("maximum element",max(tup2))
print("minimum element",min(tup2))
print('*'*10)
print('\n')
print("Question3")
a=int(input("Enter first element"))
b=int(input("Enter second element"))
c=int(input("Enter third element"))
d=int(input("Enter fourth element"))
tup3=(a,b,c,d)
mult=(tup3[0]*tup3[1]*tup3[2]*tup3[3])
print("Product is",mult)
prod=1
for i in tup3:
    prod*=i
print(prod)
print('*'*10)
print('\n')
print("SETS")
print("Question1")
p=input("Enter first value")
q=input("Enter second value")
r=input("Enter third value")
s=input("Enter fourth value")
set1=set([p,q,r,s])
print(set1)
x1=input("Enter first value")
x2=input("Enter second value")
x3=input("Enter third value")
x4=input("Enter fourth value")
set2=set([x1,x2,x3,x4])
print(set2)
set3=set1-set2
print(set3)
print('*'*10)
print('\n')
print("Question2")
set4=set1^set2
print(set4)
print('*'*10)
print('\n')
print("Question3")
set5=set1&set2
print(set5)

